### ISSUE TITLE
Not responding to arrows when used inside export

### ISSUE THREAD

**Issue by jpmedley** [enquirer/prompt-checkbox#4]
I have a [function exported](https://github.com/jpmedley/mdn-helper/blob/0.11.0/app.js#L47) via `module.exports` that uses prompt-checkbox in a way that is virtually identical to your enquirer.custom-checkbox.js example. When I call the function through the interface, attempting to use the arrows to move around the list, outputs characters to the screen instead of moving the cursor. The screen shot below shows this. (In terms of my project this is `node index.js find lock_man`.)

![screen shot 2018-10-09 at 1 14 11 pm](https://user-images.githubusercontent.com/8204171/46696001-f8ebd100-cbc5-11e8-874e-3b6208a80147.png)

If I [call the function directly](https://github.com/jpmedley/mdn-helper/blob/0.11.0/app.js#L12) my code works exactly as expected. (In this case I'm running `node app.js`.)

**Comment by jpmedley** [comment]
This turned out to be the symptom of an unrelated problem. Sorry to clog your issues list.

**Comment by doowb** [comment]
I'm glad you figured it out. I was just looking to see if something stuck out to me, but I didn't notice anything.

**Comment by jonschlinkert** [comment]
Thanks @jpmedley, fwiw we're also about to publish a new version that should be a lot easier to use, customize and debug.

**Comment by jpmedley** [comment]
FWIW, I had stdin and stdout occupied in another piece of code.
